### PR TITLE
test(Column): add snapshot test

### LINKED ISSUE #29: Add Column-tests
## Expected Behavior
Add test to `Column` component.

## Current Behavior
There are no test in `Column` component.

## Steps to Reproduce
1. Run `yarn test`.

### PR DESCRIPTION
**Pull request by jillney**
**Summary**
Changes:
- Add snapshot tests for `Column`.

This PR fixes/implements the following **bugs/features**
* [ ] Add Column-tests
* [ ] Add Column.web-tests

**Test plan (required)**
1. Run `yarn test`.

**Closing issues**
Closes #29

### CODE REVIEW

File: __tests__/Column-tests.js [hunk 1]
```diff
@@ -0,0 +1,636 @@
...
+      <Column xs={9} sm={10} md={11} lg={12} screen={screen} />
+    </ThemeProvider>,
+  ).toJSON();
+  expect(tree).toMatchSnapshot();
+});
+
+// Test NOT Absolute, Case: 'lg'
+testDescription = 'Column should render View with {"width": "91.66666667%"}.\n';
+testData = 'Test Data: screen.type="lg" lg=null md={11}';
+test(testDescription + testData, () => {
```
Comment (CareLuLu-Gabriel) [inline __tests__/Column-tests.js]: Is this format `testDescription` + `testData` a standard? Just curious why we are doing `test(testDescription + testData, () => {...})`

Comment (jillney) [reply __tests__/Column-tests.js]: Hi Gabriel, Good day! It is not a standard. Nonetheless, it is recommended to tell the purpose of a particular test. Hence, I have decided to input the test description and the test data. This is to easily read the snapshots and to easily identify if there's a need to update the snapshot when the tests are failing.

Comment (CareLuLu-Gabriel) [reply __tests__/Column-tests.js]: Got it!
