### PR TITLE
test(View): add snapshot test

### LINKED ISSUE #25: Add View-tests
## Expected Behavior
Add test to View component.

## Current Behavior
There are no test in View component.

## Steps to Reproduce (for bugs)
1. Run `yarn test`.

### PR DESCRIPTION
**Pull request by jillney**
**Summary**

Changes:
- Add `react`, `react-native`, `jest`, `babel-jest`,
`react-test-renderer` to dev dependencies.
- Add preset in `babel.config.js`
- Add snapshot tests for `View`.

This PR fixes/implements the following **bugs/features**

* [ ] Add View-tests

**Test plan (required)**

1. Run `yarn test`

**Closing issues**

Closes #25

### CODE REVIEW

File: __tests__/View-tests.js [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import React from 'react';
+import renderer from 'react-test-renderer';
+import View from '../src/View';
+import { Provider as ThemeProvider } from '../src/Theme';
+
+test('renders correctly', () => {
+  const tree = renderer.create(
+    <ThemeProvider>
+      <View />
```
Comment (CareLuLu-Gabriel) [inline __tests__/View-tests.js]: To be more complete, we should test sending `className` and `children`.

```
test('renders correctly', () => {
const tree = renderer.create(
    <ThemeProvider>
      <View className="Test__parent">
        <View className="Test__child" />
      </View>
    </ThemeProvider>
).toJSON();
expect(tree).toMatchSnapshot();
```
